### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by mintyPT** [timothycrosley/cruft#25]
Is this dead?

**Comment by timothycrosley** [comment]
Not dead, just not highly developed and already does what I needed it to do. Always happy to have new maintainers. Since I don't get paid to work on open source, I work on projects in priority of what I need done & community usage, and this one so far has had fairly low community usage, so I've invested more time into isort which has had a lot: https://timothycrosley.github.io/isort/. Really, don't know how to handle this limited time thing since my ambitions exceed my time  ¯\_(ツ)_/¯ Always appreciate advice on the matter.

Thanks!

~Timothy

**Comment by samj1912** [comment]
I would be interested in helping maintain this if you are looking for help :)

I am currently working on implementing cruft internally at my workplace and I have a fair knowledge of cookiecutter internals. I also wrote https://github.com/samj1912/CookieS which is a web front-end to cookiecutter. 

Apart from this I also maintain https://github.com/PyCQA/pydocstyle and a bunch of repositories at https://github.com/metabrainz

**Comment by timothycrosley** [comment]
@samj1912 Awesome! Thanks for the offer, and your other great contributions to the community :) I've added you as a collaborator so that you'll be able to accept pull requests etc

**Comment by samj1912** [comment]
I guess we have now addressed this. Closing this issue for now :)
