### ISSUE TITLE
cruft update fails but updates commit

### ISSUE THREAD

**Issue by rl-michaelbrandeis** [timothycrosley/cruft#8]
Mac Os 10.14.6
Cruft 1.1.2

cruft update gives error:
Apply diff and update [y/n/s]? y
patch: unrecognized option `--merge'
patch: Try `patch --help' for more information.

The .cruft.json file gets updated with new commit number and thinks the update was applied

**Comment by lsorber** [comment]
Having the same issue, even for very simple patches.

**Comment by davidedmonds** [comment]
Managed to work around this using the GNU patch tool, instead of OSX's built-in version, as that recognises the `--merge` option being used. Using homebrew, it was `brew install gpatch` to get that added.

**Comment by lsorber** [comment]
Thanks for the workaround @davidedmonds.

**Comment by metall0id** [comment]
Having the same issue here on my Mac running Catalina.

I patched it locally on my machine to use

`patch -p1 --no-backup-if-mismatch`

instead of

`patch -p1 --merge`

I understand that this is not really the same thing but this project is so useful I wanted an immediate fix.

A question for the author @timothycrosley: if I were to implement a fix for this how would you like it done? I could:
* Add a check for Darwin platform and run the command I posted above. This doesn't really give the same merge behaviour but is really non-intrusive
* Use a library like https://github.com/google/diff-match-patch. This doesn't really give the same elegant patch output as `git diff` and is quite an overhaul
* Bundle a zipped `patch` binary for Mac that is extracted and used if platform is Darwin. A zipped included binary will add about ~95KB to the package size

Other suggestions?

**Comment by jacques-** [comment]
+1 - Also stuck on this issue.

**Comment by jacques-** [comment]
Any progress here? 

sed one-liner while we wait for a more permanent solution:

`sed -i "" 's/--merge/--no-backup-if-mismatch/g' /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cruft/api.py`

**Comment by Peter200lx** [comment]
I don't have a mac to try with, but if someone wants to test here's a patch to try using `--merge` but falling back if it fails to find the option:
https://github.com/Peter200lx/cruft/commit/b12ec1cf54bbb83faf13cbf33c8f40e9b83dbcd9
https://github.com/Peter200lx/cruft/tree/bug-patch

**Comment by tyrone-push-security** [comment]
It is @metall0id here under a different account.

Works great @Peter200lx! I extended your fork to use a bundled GNU patch for Mac too. The behaviour of `no-backup-if-mismatch` is quite different and annoying.

See:
https://github.com/tyrone-push-security/cruft/tree/bundled-patch
https://github.com/tyrone-push-security/cruft/commit/53a043457c745e1466a97be9f5e8cf42209456f0

**Comment by Peter200lx** [comment]
Interesting, I think we'd want to have a check for `os.platform == "darwin"` before using a binary specific to OSX though.

**Comment by tyrone-push-security** [comment]
Fair enough, happy to make that change. I realised that I also might be able to optimise the code by not copying the binary to a temporary location before executing it. It sits on disk anyway so could probably just `chmod` and execute it directly.

I suppose the thing I want to know is: is this approach of executing a binary on Mac good enough to be pulled into the mainline? I would really like to see it pulled in after due scrutiny otherwise I'm doomed to maintaining a fork 🙂
